
version: '3'

services:

  master:
    image: 2357gi/apache-spark:latest
    ports:
      - 4040:4040
      - 8080:8080
      - 8888:8888
    volumes:
      - ./data:/src
    command: /spark/bin/spark-class org.apache.spark.deploy.master.Master --host 0.0.0.0

  worker:
    image: 2357gi/apache-spark:latest
    depends_on:
      - master
    ports:
      - 8081-8089:8081
    volumes:
      - ./data:/src
    command: /spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077 --host 0.0.0.0
